### ISSUE TITLE
[write_forcing] option should update timestamps in config folder

### ISSUE THREAD

**Issue by sibrenloos** [Deltares/hydromt_delwaq#30]
When using [write_forcing] option the dynamic maps are written, but the corresponding timestamps are not updated in the config folder files such as:
B2_timers_only.inc
B2_timers.inc
B2_outputtimes.inc
B1_timestamp.inc

**Comment by hboisgon** [comment]
It is the same for hydromt-wflow, user specifies then both write_forcing and write_config in the configuration file. If it makes sense for delwaq we can instead always start with a write_config in the first line of write_forcing.

**Comment by hboisgon** [comment]
@sibrenloos : are you okay with the user specifying write_config as well in their hydromt update file (cf example in https://github.com/Deltares/hydromt_delwaq/blob/soil/examples/delwaq_update_EM_forcing.yml), or you want to include a write_config within the write_forcing function to force it?
If not, then I can close this issue.

**Comment by sibrenloos** [comment]
we can close this issue. Let's stay aligned with the rest.

We also have a write: option. Is that doing both
write_config: 
and 
write_forcing:
? or outdated?

By the way I encountered an issue when using yml instead of ini. With yml is cannot read the starttime properly

**Comment by hboisgon** [comment]
Yes the write option includes everything so write_config and write_forcing indeed.

For the time format, indeed with yaml format we need to be a little more specific as in the example file in the link from my previous post:
![image](https://github.com/Deltares/hydromt_delwaq/assets/45457510/aba72fe4-4c55-4733-a46d-50576aade7fb)
